-- V$SQL_MONITOR.REPORT_ID = DBA_HIST_REPORT.REPORT_ID 
-- TX-LOCK 에 의해 대기 세션은 아래 GV$SQL_MONITOR 로 확인 불가 -> 등록 되지 않는다.
-- 아래 조건 쿼리를 자동으로 V$SQL_MONITOR 에 자동으로 등록됨 
-- 1) 실행 시간이5초 이상 수행  2) 병렬 수행 쿼리 3) MONITOR HINT 쿼리
-- 4) 실행계획 라인수가 300 라인 이상 시, 등록되지 않는다  EX) alter system set "_sqlmon_max_planlines'=800
-- 2019.12.27 PNC 맥스게이지에서 7초 걸리는 쿼리가 V$SQL_MONITOR 에는 등록되지 않고, 조회되지 않았음
-- WestPorts : 69xnakp8cgqjn
SELECT KEY  -- ,REPORT_ID    -- cvnz18zxk8x84 
         , INST_ID
         , USERNAME, STATUS, SERVICE_NAME, MODULE, ACTION, PROGRAM     
         , ROUND(ELAPSED_TIME/1000) AS ELAPSED_ms, ROUND(CPU_TIME/1000) AS CPU_ms,  ROUND(USER_IO_WAIT_TIME/1000) AS IO_ms
         , SQL_EXEC_START, SQL_ID, SQL_PLAN_HASH_VALUE
        , PLSQL_ENTRY_OBJECT_ID, PLSQL_ENTRY_SUBPROGRAM_ID, PLSQL_OBJECT_ID,PLSQL_SUBPROGRAM_ID
        , ( SELECT OWNER||'.'||OBJECT_NAME||' - '||OBJECT_TYPE FROM DBA_OBJECTS O WHERE O.OBJECT_ID = PLSQL_ENTRY_OBJECT_ID ) AS TOP_PLSQL_INFO  
        , ( SELECT OWNER||'.'||OBJECT_NAME||' - '||OBJECT_TYPE FROM DBA_OBJECTS O WHERE O.OBJECT_ID = PLSQL_OBJECT_ID ) AS CUR_PLSQL_INFO       
        , SQL_ID,  SQL_EXEC_ID, FIRST_REFRESH_TIME, LAST_REFRESH_TIME, REFRESH_COUNT
        , BINDS_XML  -- Bind 변수 확인 가능
        , SID, SESSION_SERIAL#, PX_MAXDOP, PX_IS_CROSS_INSTANCE, PX_MAXDOP_INSTANCES
        , PROCESS_NAME, SQL_ID, SQL_PLAN_HASH_VALUE, SQL_CHILD_ADDRESS,  IS_FULL_SQLTEXT
          BUFFER_GETS, DISK_READS, IO_INTERCONNECT_BYTES
        , ROUND(APPLICATION_WAIT_TIME/1000) AS APP_ms, ROUND(CONCURRENCY_WAIT_TIME/1000) CON_ms
        , ROUND(CLUSTER_WAIT_TIME/1000) AS CLU_ms, ROUND(USER_IO_WAIT_TIME/1000) AS IO_ms
        , ROUND(PLSQL_EXEC_TIME/1000) AS PLSQL_ms, ROUND(JAVA_EXEC_TIME/1000) AS JAVA_ms
        , SUBSTR(SQL_TEXT,1,100) AS SQL_INFO
        , ERROR_NUMBER, ERROR_MESSAGE, ERROR_FACILITY  
FROM  GV$SQL_MONITOR 
WHERE 1=1
AND  USERNAME NOT IN ('SYS','DBSNMP') 
--AND   USERNAME IS NOT NULL 
-- AND   MODULE  ='Job Trigger'
 -- AND   SQL_ID ='6b192wpds7cb6'
AND   SQL_EXEC_START > SYSDATE -  (30*60)/(24*60*60) -- 1/24 -- ()/(24*60) -- (630*10)/(24*60) -- 9rz4bj9ay8gu7 0x616b08qtwxz c9shn8nzhapwg 3z09jqqmkba1h
--AND   SQL_TEXT LIKE '%/* [SQLID:EmptyAssignment.selectEmptyPickupForAlreadyPickedUp] */%'
-- AND    SQL_ID = 'fch8hmv5nbhkx'  -- 10su9az2namnn
--AND    MODULE = 'JDBC Thin Client'
 -- ORDER BY ELAPSED_TIME desc , SQL_EXEC_START DESC , SQL_EXEC_ID ; 
 -- TOSMGT Job Trigger SendBondOut 10su9az2namnn
 ORDER BY SQL_EXEC_START DESC ;